module.exports = {
    "GANNERAL_SUCCESS": 0,
    "PAY_LOAD_ERROR": 3,
    "REPORT_STATUS_ERROR": 5,
    "DATABASE_ERROR": 11,
    "PERMISSION_DENIED": 13,
    "DATA_NOT_EXIST": 15,
    "FILE_NOT_EXIST": 16,
    "FOLDER_NOT_EXIST": 17,
    "CLOZE_AND_TOPIC_NOT_NULL": 20,
    "REPLACE_PUBLIC_TEMPLATE_NAME_ERROR": 34,
    "DATA_IS_EXIST": 40,
    "FILE_IS_EXIST": 41,
    "FOLDER_IS_EXIST": 42,
    "NO_ORTHER_VERSION_ERROR": 51,
    "READ_FILE_ERROR": 54,
    "WRITE_FILE_ERROR": 55,
    "GANNERAL_ERROR": 999
}